### ISSUE TITLE
version model missing. cannot install

### ISSUE THREAD

**Issue by huang-xin-lei** [HaseloffLab/CellModeller#37]
version model missing. cannot install
C:\Users\Administrator\Desktop\CellModeller-master\CellModeller-master>python setup.py
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    version_git = subprocess.check_output(["git", "describe"]).rstrip()
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    with open(version_py, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'CellModeller/version.py'

C:\Users\Administrator\Desktop\CellModeller-master\CellModeller-master>python setup.py
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    version=str(version_git)
NameError: name 'version_git' is not defined

**Comment by huang-xin-lei** [comment]
The problem has been solved

**Comment by waterfleas** [comment]
how did you solve it?

**Comment by huang-xin-lei** [comment]
> how did you solve it?

把前面安装的文件重新删除，直接克隆到本地，然后用conda安装的
Re delete the previously installed files, directly clone them locally, and then install them with CONDA

**Comment by huang-xin-lei** [comment]
Reinstall




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stuart ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HaseloffLab/CellModeller] version model missing. cannot install (Issue #37)





 
how did you solve it?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
